# Generated by Django 4.0.1 on 2022-09-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
    ]
